version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    automerged_updates:
      enabled: false
    # Optionally ignore specific versions or groups
    # ignore:
    #   - dependency-name: "some-package"
    #     versions: ["1.x.x"]
