name: Dependency audit and updates

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1' # weekly on Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Run npm audit
        run: |
          npm audit --json > audit.json || true
          jq '.metadata.vulnerabilities' audit.json
      - name: Fail on critical vulnerabilities
        run: |
          CRITICAL_COUNT=$(jq '.metadata.vulnerabilities.critical' audit.json)
          echo "critical vulnerabilities: $CRITICAL_COUNT"
          if [ "$CRITICAL_COUNT" -gt 0 ]; then
            echo "Critical vulnerabilities detected. Failing workflow."
            exit 1
          fi
